name: CI DevOps 2024

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout your GitHub code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Build your app with the latest command
      - name: Build and test with Maven
        working-directory: simple-api
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=MaxenceJRY_devops-livecoding -Dsonar.organization=maxencejry -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./pom.xml

  # Define job to build and publish Docker image
  build-and-push-docker-image:
    needs: test-backend
    # Run only when code is compiling and tests are passing
    if: github.ref == 'refs/heads/main' && needs.test-backend.result == 'success'
    runs-on: ubuntu-22.04

    # Steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.Docker_Hub_Username }} -p ${{ secrets.Docker_Hub_Token }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # Relative path to the place where source code with Dockerfile is located
          context: ./simple-api
          # Note: tags have to be all lower-case
          tags: ${{ secrets.Docker_Hub_Username }}/tp-devops-simple-api:latest
          push: true

      - name: Build image and push database
        # Do the same for the database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{ secrets.Docker_Hub_Username }}/tp-devops-database:latest
          push: true

      - name: Build image and push httpd
        # Do the same for httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http-server
          tags: ${{ secrets.Docker_Hub_Username }}/tp-devops-httpd:latest
          push: true
